In [1]:
# Come facciamo per accedere ad un elemento in particolare?
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] 

print(mat[1][2])

7


In [11]:
import math
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

print(math.sin(mat[1][3]))
print(math.cos(mat[2][3]))
print(math.factorial(mat[2][4]))
print(math.pi)
math.degrees(math.pi)

0.9893582466233818
0.9074467814501962
87178291200
3.141592653589793


180.0

In [13]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [36]:
# trasformiamola in un array NumPy (casting):
import numpy as np
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst_array = np.array(lst)
val_min = min(lst_array)
val_max = max(lst_array)
ven_max_4999 = lst_array[lst_array < 4999]# creo un array con valori superiori a 4999
ven_min_3000 = lst_array[lst_array >3000]# creo array con valori inferiori a 3000

print(val_min)
print(val_max)
print(ven_max_4999)
print(len(ven_max_4999))
print(ven_min_3000)
print(np.mean(lst_array))# stampo la media con np.mean

1280
8150
[2000 4320 1280 1900 2500 3900]
6
[5500 7200 4320 3900 6410 8150 7100 5350]
4634.166666666667


In [55]:
import pandas as pd

fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

#fatturati_dict[1997] 
#fatturati_series[1997]
print(fatturati_dict[1997]) # stampo chiamando la chiave
print(fatturati_series[0]) # non funziona perchè ci sono gli indici personalizzati 

12000


KeyError: 0

In [60]:
# L'azienda ci chiede di raddoppiare tutti gli stipendi
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

for i in range(len(stipendi)) :# uso range e len per accedere agli inidici e moltiplicarli 
    stipendi[i] *= 2 
print(stipendi)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [62]:
# L'azienda ci chiede di raddoppiare tutti gli stipendi con il masking
import numpy as np
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )
mask = stipendi > 0
stipendi[mask]*= 2
print(stipendi)



[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
